#!/usr/bin/env python3
"""
CodeCanon/sync.sh — generate agent-specific skill files from source skills + project config

Usage:
  ./CodeCanon/sync.sh                      # use .codecannon.yaml in current dir
  ./CodeCanon/sync.sh --config path/to/config.yaml
  ./CodeCanon/sync.sh --force              # overwrite customized files without prompting
  ./CodeCanon/sync.sh --dry-run            # preview what would be written, exits 1 if any writes pending
  ./CodeCanon/sync.sh --validate           # check all placeholders are defined, exits 1 if any missing
  ./CodeCanon/sync.sh --skill start        # sync only the named skill(s), comma-separated

Generated files carry a hash comment so sync.sh can detect manual edits.
If a generated file has been customized (hash mismatch), sync.sh warns and skips it.
Pass --force to overwrite, or delete the file to let sync.sh regenerate it cleanly.
"""

import sys
import os
import re
import hashlib
import argparse
from pathlib import Path

CODECANNON_DIR = Path(__file__).parent
MARKER = "generated by CodeCanon/sync.sh"
LEGACY_MARKER = "generated by agentgate/sync.sh"


def first_line_has_sync_marker(first_line):
    """True if the line was produced by this tool (current or legacy marker)."""
    return MARKER in first_line or LEGACY_MARKER in first_line


# ── YAML parsing ──────────────────────────────────────────────────────────────
# We parse a strict subset of YAML: top-level keys, one-level-deep key:value
# pairs, and simple lists. No multi-line scalars, no anchors, no complex types.

def parse_yaml_simple(text):
    """Parse a simple flat YAML structure into a dict."""
    result = {}
    current_key = None

    for raw_line in text.splitlines():
        # Strip inline comments (but not inside quoted values)
        line = raw_line
        if not line.strip() or line.strip().startswith('#'):
            continue

        indent = len(line) - len(line.lstrip())
        stripped = line.strip()

        if indent == 0:
            if ':' in stripped:
                key, _, value = stripped.partition(':')
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                current_key = key
                if value:
                    result[key] = value
                else:
                    result[key] = {}
        elif indent >= 2 and current_key is not None:
            if stripped.startswith('- '):
                value = stripped[2:].strip().strip('"').strip("'")
                if not isinstance(result.get(current_key), list):
                    result[current_key] = []
                result[current_key].append(value)
            elif ':' in stripped and isinstance(result.get(current_key), dict):
                key, _, value = stripped.partition(':')
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                result[current_key][key] = value

    return result


def parse_frontmatter(text):
    """Extract YAML frontmatter between --- delimiters. Returns (fm_dict, body_str)."""
    match = re.match(r'^---\n(.*?)\n---\n(.*)', text, re.DOTALL)
    if not match:
        return {}, text.strip()
    fm_text, body = match.group(1), match.group(2)
    fm = {}
    for line in fm_text.splitlines():
        if ':' in line:
            key, _, value = line.partition(':')
            raw_val = value.strip().strip('"').strip("'")
            # Handle YAML lists on a single line: [a, b, c]
            if raw_val.startswith('[') and raw_val.endswith(']'):
                fm[key.strip()] = [v.strip().strip('"') for v in raw_val[1:-1].split(',')]
            else:
                fm[key.strip()] = raw_val
    return fm, body.strip()


# ── Placeholder substitution ──────────────────────────────────────────────────

def apply_placeholders(text, values):
    """Replace {{KEY}} tokens with configured values."""
    for key, value in values.items():
        text = text.replace('{{' + key + '}}', value)
    return text


def find_unresolved(text):
    """Return list of placeholder names that were not substituted."""
    return re.findall(r'\{\{([A-Z_]+)\}\}', text)


# ── Hash and change detection ─────────────────────────────────────────────────

def content_hash(text):
    return hashlib.md5(text.encode()).hexdigest()[:8]


def read_file_info(file_path):
    """
    Inspect an existing file for Code Cannon provenance (current or legacy sync marker).

    Returns (stored_hash, body_hash, is_generated) where:
      stored_hash — hash recorded in the marker line when the file was last written
      body_hash   — hash of the file's actual content (after the marker line)
      is_generated — True if the file was written by this sync tool (current or legacy marker)

    Comparing stored_hash vs body_hash tells us whether the file was edited
    after the last sync. Comparing body_hash vs the freshly-computed h tells
    us whether the file already matches what we'd generate today.
    """
    path = Path(file_path)
    if not path.exists():
        return None, None, False

    content = path.read_text()
    parts = content.split('\n', 1)
    first_line = parts[0]

    if not first_line_has_sync_marker(first_line):
        return None, None, False

    match = re.search(r'hash: ([a-f0-9]+)', first_line)
    stored_hash = match.group(1) if match else None

    body = parts[1] if len(parts) > 1 else ''
    body_hash = content_hash(body)

    return stored_hash, body_hash, True


# ── Adapter loading ───────────────────────────────────────────────────────────

def load_adapter(adapter_name):
    """Load adapter config and header template."""
    adapter_dir = CODECANNON_DIR / 'adapters' / adapter_name
    config_path = adapter_dir / 'config.yaml'
    header_path = adapter_dir / 'header.md'

    if not config_path.exists():
        print(f"  Error: adapter '{adapter_name}' not found at {adapter_dir}/")
        return None

    config = parse_yaml_simple(config_path.read_text())
    header = header_path.read_text() if header_path.exists() else ''

    return {
        'name': adapter_name,
        'output_directory': config.get('output_directory', f'.{adapter_name}'),
        'output_extension': config.get('output_extension', '.md'),
        'header_template': header,
    }


def build_header(adapter, skill_name, fm):
    """Render the adapter's invocation header for a specific skill."""
    template = adapter['header_template']
    description = fm.get('description', skill_name)
    header = template.replace('{skill}', skill_name).replace('{description}', description)
    return header


# ── Main sync logic ───────────────────────────────────────────────────────────

def sync_skill(skill_path, adapter, project_config, project_root, args):
    """Sync a single skill file to the adapter's output directory."""
    raw = skill_path.read_text()
    fm, body = parse_frontmatter(raw)

    skill_name = fm.get('skill', skill_path.stem)
    no_header = fm.get('no_invocation_header', 'false').lower() == 'true'
    output_path_override = fm.get('output_path_override', '')

    # Apply placeholder substitution
    body = apply_placeholders(body, project_config)
    if output_path_override:
        output_path_override = apply_placeholders(output_path_override, project_config)

    # Warn about unresolved placeholders
    unresolved = find_unresolved(body)
    if unresolved:
        print(f"  Warning: {skill_name} has unresolved placeholders: {', '.join(unresolved)}")

    # Build full content
    header = '' if no_header else build_header(adapter, skill_name, fm)
    full_content = header + body + '\n'

    # Determine output path
    if output_path_override:
        out_path = project_root / output_path_override
    else:
        ext = adapter['output_extension']
        out_dir = project_root / adapter['output_directory']
        out_path = out_dir / f"{skill_name}{ext}"

    # Compute hash (of content, before marker line)
    h = content_hash(full_content)
    marker_line = f"<!-- {MARKER} | skill: {skill_name} | adapter: {adapter['name']} | hash: {h} | DO NOT EDIT — run CodeCanon/sync.sh to regenerate -->\n"
    final_content = marker_line + full_content

    # Check existing file
    stored_hash, body_hash, is_generated = read_file_info(out_path)

    skill_type = fm.get('type', 'skill')
    type_tag = f" [{skill_type}]" if skill_type != 'skill' else ''

    # body_hash is computed over the file content after the marker line,
    # which is exactly what we'd write as full_content. If they match, we're done.
    if body_hash == h:
        print(f"  ✓ {skill_name}{type_tag} (up to date)")
        return False

    if out_path.exists() and not is_generated and not args.force:
        print(f"  ⚠ {skill_name}{type_tag} (file exists but was not generated by Code Cannon sync — skipping, use --force to overwrite)")
        return False

    if is_generated and not args.force:
        if body_hash != stored_hash:
            # File was edited after the last sync (body no longer matches stored hash)
            print(f"  ⚠ {skill_name}{type_tag} (customized since last sync — skipping, use --force to overwrite)")
            return False
        # body_hash == stored_hash but != h: source skill changed, file unmodified → safe to regenerate

    # Write
    if args.dry_run:
        print(f"  → {skill_name}{type_tag} (would write to {out_path})")
        return True
    else:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(final_content)
        action = "updated" if out_path.exists() else "written"
        print(f"  ✓ {skill_name}{type_tag} ({action} → {out_path})")
        return False


def validate_placeholders(skill_files, project_config):
    """Scan all skills for {{PLACEHOLDER}} tokens; error if any are undefined."""
    errors = []
    for skill_path in skill_files:
        raw = skill_path.read_text()
        _, body = parse_frontmatter(raw)
        missing = [p for p in find_unresolved(body) if p not in project_config]
        for p in missing:
            errors.append(f"  {skill_path.name}: {{{{{p}}}}} not defined in config")
    return errors


def main():
    parser = argparse.ArgumentParser(
        description='Generate agent-specific skill files from Code Cannon skills/')
    parser.add_argument('--config', default='.codecannon.yaml',
                        help='Path to project config (default: .codecannon.yaml)')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite customized files without prompting')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be written without writing anything. Exits non-zero if any writes are pending.')
    parser.add_argument('--validate', action='store_true',
                        help='Pre-flight check: verify all {{PLACEHOLDERS}} in skills are defined in config. Exits non-zero if any are missing. Does not write files.')
    parser.add_argument('--skill', default='',
                        help='Sync only specific skill(s), comma-separated (e.g. start,ship)')
    args = parser.parse_args()

    project_root = Path.cwd()

    # Load project config
    config_path = project_root / args.config
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}")
        print(f"Copy {CODECANNON_DIR}/templates/codecannon.yaml to .codecannon.yaml and customize it.")
        sys.exit(1)

    raw_config = parse_yaml_simple(config_path.read_text())
    adapters_list = raw_config.get('adapters', [])
    project_config = raw_config.get('config', {})

    if not adapters_list:
        print("Error: no adapters specified in config. Add 'adapters: [claude]' to .codecannon.yaml")
        sys.exit(1)

    # Determine which skills to sync
    skills_dir = CODECANNON_DIR / 'skills'
    all_skill_files = sorted(skills_dir.glob('*.md'))

    if args.skill:
        requested = {s.strip() for s in args.skill.split(',')}
        skill_files = [f for f in all_skill_files if f.stem in requested]
        if not skill_files:
            print(f"Error: no matching skills found for: {args.skill}")
            sys.exit(1)
    else:
        skill_files = all_skill_files

    # --validate: pre-flight placeholder check, no writes
    if args.validate:
        errors = validate_placeholders(skill_files, project_config)
        if errors:
            print("Validation failed — undefined placeholders:\n")
            for e in errors:
                print(e)
            sys.exit(1)
        else:
            print("Validation passed — all placeholders are defined.")
        return

    if args.dry_run:
        print("Dry run — no files will be written.\n")

    # Sync each adapter
    any_pending = False
    for adapter_name in adapters_list:
        adapter = load_adapter(adapter_name)
        if not adapter:
            continue

        print(f"\n[{adapter_name}] → {adapter['output_directory']}/")

        for skill_path in skill_files:
            would_write = sync_skill(skill_path, adapter, project_config, project_root, args)
            if would_write:
                any_pending = True

    print("\nDone.")

    if args.dry_run and any_pending:
        sys.exit(1)


if __name__ == '__main__':
    main()
